name = "kovka53"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
CONTACT_EMAIL = "kovka53sup@mail.ru"
RESEND_FROM_EMAIL = "noreply@kovka53.ru"
SITE_URL = "https://kovka53.ru"
